apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-account
  namespace: sample-mcs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservices-role
  namespace: sample-mcs
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "configmaps", "secrets" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservices-binding
  namespace: sample-mcs
subjects:
  - kind: ServiceAccount
    name: microservices-account
roleRef:
  kind: Role
  name: microservices-role
  apiGroup: rbac.authorization.k8s.io