openapi: 3.0.3

info:
  title: Person API
  version: 1.0.0

paths: {}

components:
  schemas:
    Person:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer